insert into employees(email, first_name, last_name,salary) values('tony_stark@gmail.com', 'Tony', 'Stark', 20000);
insert into employees(email, first_name, last_name,salary) values('chris_pang@gmail.com', 'Chris', 'Pang', 4000);
insert into employees(email, first_name, last_name,salary) values('constance_wu@gmail.com', 'Constance', 'Wu', 5000);
insert into employees(email, first_name, last_name,salary) values('henry_golding@gmail.com', 'Henry', 'Golding', 8000);
insert into employees(email, first_name, last_name,salary) values('gemma_chan@gmail.com', 'Gemma', 'Chan', 12000);
insert into employees(email, first_name, last_name,salary) values('jackie_chan@gmail.com', 'Jackie', 'Chan', 6000);
insert into employees(email, first_name, last_name,salary) values('tommy_koh@yahoo.com', 'Tommy', 'Koh', 13000);
insert into employees(email, first_name, last_name,salary) values('fiona_xie@gmail.com', 'Fiona', 'Xie', 1500);
insert into employees(email, first_name, last_name,salary) values('selena_tan@gmail.com', 'Selena', 'Tan', 3300);
